
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: docker_nodejs
  name: docker_nodejs
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: docker_nodejs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: docker_nodejs
    spec:
      containers:
      - image: docker_nodejs
        imagePullPolicy: IfNotPresent
        name: docker_nodejs
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: docker_nodejs
  name: docker_nodejs
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: docker_nodejs
  sessionAffinity: None
  type: ClusterIP